;(function(window,$){"use strict";var Hideshare=function(elem,options){this.elem=elem;this.$elem=$(elem);this.options=options;};Hideshare.prototype={defaults:{link:document.URL,title:document.title,description:'',media:null,facebook:true,twitter:true,pinterest:true,googleplus:true,linkedin:true,position:"bottom",speed:100},init:function(){this.config=$.extend({},this.defaults,this.options);this.wrapHideshare();return this;},wrapHideshare:function(){var output=output,width=this.$elem.outerWidth(),height=this.$elem.outerHeight(),liWidth=0,placement=this.config.position,transition=this.config.speed,shareTitle=this.config.title,shareLink=this.config.link,shareMedia=this.config.media,shareDescription=this.config.description,facebookTemplate='<li><a class="hideshare-facebook" href="#"><i class="fa fa-facebook-square fa-2x"></i><span>Facebook</span></a></li>',twitterTemplate='<li><a class="hideshare-twitter" href="#"><i class="fa fa-twitter-square fa-2x"></i><span>Twitter</span></a></li>',pinterestTemplate='<li><a class="hideshare-pinterest" href="#" data-pin-do="buttonPin" data-pin-config="above"><i class="fa fa-pinterest-square fa-2x"></i><span>Pinterest</span></a></li>',googleplusTemplate='<li><a class="hideshare-google-plus" href="#"><i class="fa fa-google-plus-square fa-2x"></i><span>Google Plus</span></a></li>',linkedinTemplate='<li><a class="hideshare-linkedin" href="#"><i class="fa fa-linkedin-square fa-2x"></i><span>Linked In</span></a></li>';if(this.config.facebook){output=facebookTemplate;liWidth+=40;}else{output="";liWidth=liWidth;}
if(this.config.twitter){output+=twitterTemplate;liWidth+=40;}else{output=output;liWidth=liWidth;}
if(this.config.pinterest){output+=pinterestTemplate;liWidth+=40;}else{output=output;liWidth=liWidth;}
if(this.config.googleplus){output+=googleplusTemplate;liWidth+=40;}else{output=output;liWidth=liWidth;}
if(this.config.linkedin){output+=linkedinTemplate;liWidth+=40;}else{output=output;liWidth=liWidth;}
if(liWidth<width){liWidth=width;}
var hideshareList='<ul class="hideshare-list" style="display: none; width: '+liWidth+'px'+'">'+output+'</ul>';this.$elem.addClass("hideshare-btn").wrap("<div class='hideshare-wrap' />");$(hideshareList).insertAfter(this.$elem);var getPlacement=function(placement,width,height,speed,element){var styles={};if(placement==="right"){styles={"left":width+10+"px","right":-(width+10)+"px","opacity":"toggle"};}else if(placement==="left"){styles={"left":-(width+10)+"px","right":width+10+"px","opacity":"toggle"};}else if(placement==="top"){styles={"top":-(height+10)+"px","bottom":height+10+"px","opacity":"toggle"};}else{styles={"top":height+4+"px","bottom":-(height+4)+"px","left":"0px","opacity":"toggle"};}
element.animate(styles,speed).addClass("shown");};var returnPlacement=function(speed,element){var styles={"top":"0px","left":"0px","opacity":"toggle"};element.animate(styles,speed).removeClass("shown");};this.$elem.click(function(){var list=$(this).next(".hideshare-list");if(!list.hasClass("shown")){getPlacement(placement,width,height,transition,list);}
$('.hideshare-wrap').mouseleave(function(){if(list.hasClass("shown")){returnPlacement(transition,list);}});return false;});var shareFacebook=function(shareURL,shareImage){window.open('//www.facebook.com/share.php?m2w&s=100&p[url]='+encodeURIComponent(shareURL)+'&p[images][0]='+encodeURIComponent(shareImage)+'&p[title]='+encodeURIComponent(shareTitle)+'&p[summary]='+encodeURIComponent(shareDescription),'Facebook','menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');};var shareTwitter=function(shareURL,shareImage){window.open('https://twitter.com/intent/tweet?original_referer='+encodeURIComponent(shareURL)+'&text='+encodeURIComponent(shareTitle)+'%20'+encodeURIComponent(shareURL),'Twitter','menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');};var sharePinterest=function(shareURL,shareImage){window.open('//pinterest.com/pin/create/button/?url='+encodeURIComponent(shareURL)+'&media='+encodeURIComponent(shareImage)+'&description='+encodeURIComponent(shareTitle),'Pinterest','menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');};var shareGooglePlus=function(shareURL,shareImage){window.open('//plus.google.com/share?url='+encodeURIComponent(shareURL),'GooglePlus','menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');};var shareLinkedIn=function(shareURL){window.open('//www.linkedin.com/shareArticle?mini=true&url='+encodeURIComponent(shareURL)+'&title='+encodeURIComponent(shareTitle)+'&source='+encodeURIComponent(shareURL),'LinkedIn','menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');};var new_shareLink=function(element){var new_shareLink=element.parents('.hideshare-wrap').find('.share').attr('href');if(new_shareLink!=""||new_shareLink!="#"){new_shareLink=new_shareLink;}else{new_shareLink=shareLink;}
return new_shareLink;}
var new_shareMedia=function(element){var new_shareMedia=element.parents('.hideshare-wrap').find('.share').data('image');if(new_shareMedia!=""){new_shareMedia=document.domain+new_shareMedia;}else{new_shareMedia=shareMedia;}
return new_shareMedia;}
$(".hideshare-facebook").click(function(){shareFacebook(new_shareLink($(this)),new_shareMedia($(this)));return false;});$(".hideshare-twitter").click(function(){shareTwitter(new_shareLink($(this)),new_shareMedia($(this)));return false;});$(".hideshare-pinterest").click(function(){sharePinterest(new_shareLink($(this)));return false;});$(".hideshare-google-plus").click(function(){shareGooglePlus(new_shareLink($(this)),new_shareMedia($(this)));return false;});$(".hideshare-linkedin").click(function(){shareLinkedIn(new_shareLink($(this)));return false;});}};Hideshare.defaults=Hideshare.prototype.defaults;$.fn.hideshare=function(options){return this.each(function(){new Hideshare(this,options).init();});};window.Hideshare=Hideshare;})(window,jQuery);