
var BrowserDetect={init:function()
{this.browser=this.searchString(this.dataBrowser)||"Other";this.version=this.searchVersion(navigator.userAgent)||this.searchVersion(navigator.appVersion)||"Unknown";},searchString:function(data)
{for(var i=0;i<data.length;i++)
{var dataString=data[i].string;this.versionSearchString=data[i].subString;if(dataString.indexOf(data[i].subString)!=-1)
{return data[i].identity;}}},searchVersion:function(dataString)
{var index=dataString.indexOf(this.versionSearchString);if(index==-1)return;return parseFloat(dataString.substring(index+this.versionSearchString.length+1));},dataBrowser:[{string:navigator.userAgent,subString:"Chrome",identity:"Chrome"},{string:navigator.userAgent,subString:"MSIE",identity:"Explorer"},{string:navigator.userAgent,subString:"Firefox",identity:"Firefox"},{string:navigator.userAgent,subString:"Safari",identity:"Safari"},{string:navigator.userAgent,subString:"Opera",identity:"Opera"}]};BrowserDetect.init();$(function(){techTrekEventFormat();if($("#friend-form").length>=1){$("#friend-form").validate({rules:{fname:"required",lname:"required",company:"required",email:{required:true,email:true},openanswer1:"required"}});}
$(".tt-destiny-btn").click(function(){$(".text-shadowbox").toggle();$(".shadowbox-bg-white").toggle();});$(".text-shadowbox-close").click(function(){$(".text-shadowbox").toggle();$(".shadowbox-bg-white").toggle();});$("#the-past-employers").click(function(){$("#view-past-employers").slideToggle();});$("#view-upcoming-events").click(function(){$("#upcoming-events-show").slideToggle();});$(".text-shadowbox-closed").click(function(){$(".shadowbox-bg-white").toggle();$(".upcoming-events-soon").toggle();});$('.cloud-bg').wrapInner('<div class="cloud-motion"></div>');$("#search-icon").click(function(){$('#uat-search').toggleClass("open-search");});$('#date-selection').change(function(){if($(this).val()=="One hour tour"){$("#date-time-selection").show();}else{$("#time-selection").hide();}});function resize_iframe()
{var height=window.innerWidth;if(document.body.clientHeight)
{height=document.body.clientHeight;}
document.getElementById("ifr").style.height=parseInt(height-
document.getElementById("ifr").offsetTop-100)+"px";window.parent.$('#tfa_416').css('display','none');}
window.onresize=resize_iframe;courseListWrapper();$(document).on('click','.expansion-list-title',function(e){e.preventDefault();var $this=$(this),parent=$this.parents('.expansion-container'),expansionContent=parent.find('.expansion-list-content');if(!expansionContent.hasClass('active')){$this.addClass('active');expansionContent.css({'height':'0'}).removeClass('hidden').addClass('active').animate({height:expansionContent[0].scrollHeight});}else{expansionContent.animate({height:0},700,function(){$this.removeClass('active');expansionContent.removeClass('active').addClass('hidden');});}});$(document).on('click','#submit-rsvp',function(){$('#rsvp-form').validate({rules:{email:{required:true,email:true},phone:{required:true,phoneUS:true}},messages:{fname:"Enter your first name",lname:"Enter your last name",email:"Enter a valid e-mail address",address:"Enter your address",city:"Enter your city",address:"Enter your state",attend:"Select when you would like to attend",phone:"Enter a valid phone number",highschool:"Enter your high school",graduationMonth:"Select a month",graduationYear:"Select a year",programInterest:"Select a program",gender:"Select your gender",numberAttending:"Enter how many people are attending",eventDate:"Select a date",permissionForm:"You must send your permission form"},errorPlacement:function(error,element){if(element.is(":radio, :checkbox")){error.insertAfter(element.parent());}else{error.insertAfter(element);}}});});$(document).on('click','[data-func="hide-show"]',function(e){e.preventDefault();hideShow($(this));});$(document).on('click','[data-func="scroll-to-anchor"]',function(e){e.preventDefault();scrollToAnchor($(this));});courseName();var $readMore=$($('div, section, p').find('[data-readmore]')),ignoreCount=$readMore.data('readmore')-1;if($readMore.length>=1){$readMore.find("p:nth-child("+$readMore.data('readmore')+")").after('<div class="button more white small readMore xtra-margin top-20-margin">Read More</div>');$readMore.find("p:last-child").after('<div class="button more white small readLess hidden xtra-margin top-20-margin">Less</div>');$readMore.find("p:gt("+ignoreCount+")").wrapAll('<div class="hidden xtra-padding top-20-padding"></div>');}
$(document).on('click','.readMore',function(){$(this).hide();$(this).parent().find('.readLess').fadeIn();$(this).parent().find('.hidden').fadeIn();});$(document).on('click','.readLess',function(){$(this).hide();$(this).parent().find('.readMore').fadeIn();$(this).parent().find('.hidden').fadeOut();});$("<select class='mobile-nav' />").appendTo("header section");$("<option />",{"selected":"selected","value":"","text":"MENU"}).appendTo(".mobile-nav");$("#top-nav nav .main-nav a").each(function(){var el=$(this);$("<option />",{"value":el.attr("href"),"text":el.text()}).appendTo(".mobile-nav");});$(".mobile-nav").change(function(){window.location=$(this).find("option:selected").val();});blogStyles();var slides=$('.nav-slider .slide-wrapper .slide'),firstSlide=slides.first(),countSlides=slides.length-1;firstSlide.addClass('active');$(document).on('click','.nav-slider .next',function(){var activeSlide=$(this).parent().find('.slide-wrapper .slide.active'),nextSlide=activeSlide.next();if(activeSlide.is(':last-child')){activeSlide.removeClass('active');firstSlide.addClass('active');}else{activeSlide.removeClass('active');nextSlide.addClass('active');}
if($(window).width()<=959){var slideBox=$(this).parents('.slideup-box'),slideHeight=$('.slide.active')[0].scrollHeight+111;slideBox.animate({height:slideHeight});}});var $slideTarget;$("#bottom-nav .slideup-nav").on({click:function(){$slideTarget=$(this).data('target');if(!$(this).hasClass('mobile')){if(!$(this).hasClass('active')){if($(window).width()>=960){$("#"+$slideTarget).animate({height:slideNavigationHeight()});}else{$("#"+$slideTarget).animate({height:singleNavigationHeight($slideTarget)});}
$(this).addClass('active');if($(window).width()<=959){$(this).addClass('mobile');}
return false;}}},mouseleave:function(){if($(window).width()>=960){$("#"+$slideTarget).animate({height:'30px'});$(this).removeClass('active');}else{return false;}}});$(document).on("click","#bottom-nav .slideup-nav h3",function(){var parentContainer=$(this).parents('.slideup-nav');$slideTarget=$(this).parents('.slideup-nav').data('target');if(parentContainer.hasClass('mobile')){if(parentContainer.hasClass('active')){$("#"+$slideTarget).animate({height:'47px'});parentContainer.removeClass('active');parentContainer.removeClass('mobile');}else{return false;}}});if($(".share").length>=1){$(".share").hideshare({position:"bottom",linkedin:false,pinterest:false});}
$("select[name='sort-by']").change(function(){hideShowAppSorter($(this).val());});if($('#application-list').length){applicationListStyles();}
if(BrowserDetect.browser!='Safari'||!BrowserDetect.browser!='Chrome'){}
if(BrowserDetect.browser!='Safari'||!BrowserDetect.browser!='Chrome'){fixHeight();}
var featuredAlumniBucket=$('#featured-alumni'),facultyAlumniChildren=featuredAlumniBucket.children('div');var featuredFacultyBucket=$('#featured-faculty'),facultyBucketChildren=featuredFacultyBucket.children('div');var featuredSipsBucket=$('#featured-student-innovation-project'),facultySipsChildren=featuredSipsBucket.children('div');if(featuredAlumniBucket.length>0){facultyAlumniChildren.eq(0).removeClass('hidden').addClass('active');}
if(featuredFacultyBucket.length>0){facultyBucketChildren.eq(0).removeClass('hidden').addClass('active');}
if(featuredSipsBucket.length>0){facultySipsChildren.eq(0).removeClass('hidden').addClass('active');}
setInterval(rotateBucket,10000);$('.header-motion').animate({'background-position':'-1640px'},60000,'linear',function(){$('.header-motion').delay(2000).animate({'background-position':'0px'},60000,'linear')});$('.header2').animate({'background-position':'1640px'},120000,'linear',function(){$('.header2').css({'background-position':'0px'})});window.setInterval("headerMotion()",120000);window.setInterval("headerMotion2()",120000);if(BrowserDetect.browser!='Safari'||!BrowserDetect.browser!='Chrome'){techTrekHeaderFix();}
heroSliderFunction();aggTabStyles();$(document).on('click','.agg-tab',function(){moveAggContent($(this));});loadFlickrGallery();});$(window).load(function(){if(BrowserDetect.browser=='Safari'||BrowserDetect.browser=='Chrome'){techTrekHeaderFix();}
if(BrowserDetect.browser=='Safari'||BrowserDetect.browser=='Chrome'){}
if(BrowserDetect.browser=='Safari'||BrowserDetect.browser=='Chrome'){fixHeight();}
if($('.heroSlider').length>=1){$('.heroSlider').css({height:$('.heroSlider')[0].scrollHeight});}
elastislideGallery();});$(window).resize(function(){if($('.techtrek-schedule .scheduled-event.overnight').length>=1){$('.scheduled-event.overnight').css({'width':$('.scheduled-event.overnight').parents('.bucket-content').width()});}
var browserWidth=$(window).width();blogStyles();if(browserWidth>=960){$(".slideup-box").each(function(){$(this).css({height:'30px'});$(this).removeClass('active');});$(".slideup-nav").each(function(){$(this).removeClass('active');$(this).removeClass('mobile');});}else{$(".slideup-box").each(function(){$(this).css({height:'47px'});});}
fixHeight();techTrekHeaderFix();aggTabStyles();if($('.heroSlider').length>=1){$('.heroSlider').css({height:$('.heroSlider')[0].scrollHeight});}})
var courseListWrapper=function(){if($('.course-list').length>=1){$('.course-list').each(function(){var courses=$(this).find('.expansion-container')
var totalCourses=courses.length;var divideCourseList=totalCourses/2;var coursePerColumn=Math.round(divideCourseList);courses.slice(0,coursePerColumn).wrapAll('<div class="content"></div>').parent().wrapAll('<div class="twelve columns"></div>');courses.slice(coursePerColumn).wrapAll('<div class="content"></div>').parent().wrapAll('<div class="twelve columns"></div>');});}}
var hideShow=function(elem){var $target=$('.'+elem.data('target')),$activeTarget='';$('[data-func="hide-show"]').each(function(){if($('.'+$(this).data('target')).hasClass('active')&&!$target.hasClass('active')){$activeTarget=$('.'+$(this).data('target'));}});if($target.hasClass('hidden')){if($activeTarget!=''){$activeTarget.animate({opacity:0},1000,function(){$activeTarget.removeClass('active').addClass('hidden');$target.css({opacity:0}).removeClass('hidden').addClass('active').animate({opacity:1},1000);});}else{$target.css({opacity:0}).removeClass('hidden').addClass('active').animate({opacity:1},1000);if($target.find('#map-canvas').length>=1){if(!$target.find('#map-canvas').hasClass('map-fixed')){googleMapRedraw();}}}}else{$target.animate({opacity:0},1000,function(){$target.removeClass('active').addClass('hidden');});}}
var hideShow=function(elem){var $target=$('.'+elem.data('target')),$activeTarget='';$('[data-func="hide-show"]').each(function(){if($('.'+$(this).data('target')).hasClass('active')&&!$target.hasClass('active')){$activeTarget=$('.'+$(this).data('target'));}});if($target.hasClass('hidden')){if($activeTarget!=''){$activeTarget.animate({opacity:0},1000,function(){$activeTarget.removeClass('active').addClass('hidden');$target.css({opacity:0}).removeClass('hidden').addClass('active').animate({opacity:1},1000);});}else{$target.css({opacity:0}).removeClass('hidden').addClass('active').animate({opacity:1},1000);if($target.find('#map-canvas').length>=1){if(!$target.find('#map-canvas').hasClass('map-fixed')){googleMapRedraw();}}}}else{$target.animate({opacity:0},1000,function(){$target.removeClass('active').addClass('hidden');});}}
var scrollToAnchor=function(elem){console.log(elem);var $target=$('#'+elem.data('target'));$('html,body').animate({scrollTop:$target.offset().top},'slow');}
var loadFlickrGallery=function(){if($('.flickr-gallery').length>=1){var getPhotoSetID=$('.flickr-gallery').data('photoset');$('div.flickr-gallery').flickr({photoset_id:getPhotoSetID});}}
var elastislideGallery=function(){if($('.flickr-gallery').length>=1){if(!$('#elastislider-lrgImage').parents('.gallery').hasClass('not-collapsed')){$('#elastislider-lrgImage').append('<div class="round-corners overlay"></div>');}
$('#horz-es-carousel').elastislide();var firstImg=$('.elastislide-list li:first-child img').attr('src');$('#elastislider-lrgImage img').attr('src',firstImg.replace('_s','_b')).parents('section').removeClass('hidden');$(document).on('click','#horz-es-carousel li a img',function(){var largeSrc=$(this).attr('src').replace('_s.jpg','_b.jpg');$('.lrgImage img').attr('src',''+largeSrc);if(!$('#elastislider-lrgImage').parents('.gallery').hasClass('not-collapsed')){$(".gallery").animate({"height":"100%"},1000,function(){$(".overlay, .galleryTitle").hide();$("#elastislider-lrgImage").append('<div class="close-me"></div>');});}});$(document).on('click','.close-me',function(){$(".overlay, .galleryTitle").show();$('.close-me').remove();$('.gallery').animate({"height":"80px"},1000);});}}
function hideShowAppSorter(sortBy){var onlyShow=sortBy;function unwrapAllApps(){var deferred=$.Deferred();if($('#application-list .application').length){$('#application-list .application').unwrap();}
deferred.resolve();return deferred.promise();}
function moveAppsToHide(){var deferred=$.Deferred();$('#application-list .application').each(function(){$(this).clone().appendTo('#hidden-applications');$(this).remove();})
deferred.resolve();return deferred.promise();}
function moveSelectedApps(){var deferred=$.Deferred();if(onlyShow=='all'||onlyShow=='alpha'){$('#hidden-applications .application').each(function(){$(this).clone().appendTo('#application-list');$(this).remove();})}else{$('#hidden-applications *[data-'+onlyShow+'="true"]').each(function(){$(this).clone().appendTo('#application-list');$(this).remove();})}
deferred.resolve();return deferred.promise();}
function sortApps(){var deferred=$.Deferred();$('#hidden-applications .application').sort(function(a,b){if(onlyShow=='alpha'){return($(a).data('alpha')<$(b).data('alpha'))?-1:($(a).data('alpha')>$(b).data('alpha'))?1:0;}else{return($(a).data('id')<$(b).data('id'))?-1:($(a).data('id')>$(b).data('id'))?1:0;}}).appendTo('#hidden-applications');deferred.resolve();return deferred.promise();}
unwrapAllApps().then(moveAppsToHide).then(sortApps).then(moveSelectedApps).then(applicationListStyles);}
var applicationListStyles=function(){var apps=$("#application-list  .application");for(var i=0;i<apps.length;i+=3){apps.slice(i,i+3).wrapAll("<div class='row application-row'></div>");}}
var blogStyles=function(){var tableWidth=$('.table-style .table-cell').width();$('.blog-share').css({'width':tableWidth});}
var slideNavigationHeight=function(){$('.slideup-box .content').css({height:'calc(100% - 31px)'});var slideNavMaxHeight=0;$('.slideup-box .content').each(function(){slideNavMaxHeight=$(this)[0].scrollHeight>slideNavMaxHeight?$(this)[0].scrollHeight:slideNavMaxHeight;});slideNavMaxHeight=slideNavMaxHeight+41;return slideNavMaxHeight;};var singleNavigationHeight=function(thisTarget){$('.slideup-box .content').css({height:'calc(100% - 31px)'});var slideNavMaxHeight=0;slideNavMaxHeight=$("#"+thisTarget)[0].scrollHeight;if($.trim($("#"+thisTarget+" .content").html()).length){slideNavMaxHeight=slideNavMaxHeight+41;}
return slideNavMaxHeight;};var majorsImgSetHeight=function(){var imgHeight=0;$('.majors-list img.degree-thumb').each(function(){imgHeight=$(this)[0].scrollHeight>imgHeight?$(this)[0].scrollHeight:imgHeight;});return imgHeight;};var fixHeight=function(elem){var parent=$('.fix-height');parent.each(function(){var element=$(this).find('[data-fix="true"]');element.css({height:0,});element.css({height:getFixHeight(element),});});}
var googleMapRedraw=function(){$('#map-canvas').html($('#map-canvas').html()).addClass('map-fixed');}
var windowWidth=$(window).width();var getFixHeight=function(elem){var elemHeight=0;elem.each(function(){if(windowWidth>480){elemHeight=$(this)[0].scrollHeight>elemHeight?$(this)[0].scrollHeight:elemHeight;}else{elemHeight=$(this)[0].scrollHeight>elemHeight?$(this)[0].scrollHeight:'auto';}});if(elemHeight==0){elem.parents('.fix-height').css({'visibility':'hidden','height':0}).removeClass('hidden');elem.each(function(){elemHeight=$(this)[0].scrollHeight>elemHeight?$(this)[0].scrollHeight:elemHeight;});elem.parents('.fix-height').css({'visibility':'visible','height':'auto'}).addClass('hidden');}
return elemHeight;};var courseName=function(){var thisCourse=$('section[data-corse-name]');if(thisCourse.length){var courseLower=thisCourse.data('corse-name').toLowerCase(),courseUpper=thisCourse.data('corse-name').toUpperCase();$('.degree-name-lower').each(function(){$(this).html(courseLower);});$('.degree-name-upper').each(function(){$(this).html(courseUpper);});}}
var aggTabStyles=function(){$('section[class*="-speaker-section"]').each(function(){var aggSection=$(this);aggtab=aggSection.find('.agg-tab'),aggtabContainer=aggtab.parent(),bucketContainer=aggSection.find('.agg-bucket-container'),aggContentExpanded=aggSection.find('.agg-content-expanded'),aggExpanded=aggSection.find('.agg-content-expanded .agg-expanded'),hiddenContent=aggSection.find('.agg-hidden-content'),rowItemNum='';if($(window).width()>=768){rowItemNum=6;}else{rowItemNum=1;}
if($(this).find('.agg-bucket-container').length>=1){aggtab.removeClass('first').removeClass('last').removeClass('active').parent().unwrap();}
if(aggContentExpanded.length>=1){if(aggExpanded.length>=1){aggExpanded.each(function(){$(this).clone().appendTo(hiddenContent);});}
aggContentExpanded.remove();}
hiddenContent.find('.agg-expanded').css({'display':'none'});for(var i=0;i<aggtabContainer.length;i+=rowItemNum){aggtabContainer.slice(i,i+rowItemNum).wrapAll("<div class='row agg-bucket-container'></div>").parents('.agg-bucket-container').after('<div class="row agg-content-expanded no-margin bottom-margin"></div>');$(this).find('.agg-bucket-container').each(function(){$(this).find('.agg-tab').first().addClass('first');$(this).find('.agg-tab').eq(rowItemNum-1).addClass('last');});}});}
var moveAggContent=function(elem){var element=elem.data('id'),targetContainer=$('div[data-id="'+element+'"]').parents('.agg-bucket-container').next('.agg-content-expanded'),target=elem.parents('section[class*="-speaker-section"]').find('.agg-hidden-content #'+element),hiddenContainer=elem.parents('section[class*="-speaker-section"]').find('.agg-hidden-content');if(target.length>=1){$('.agg-content-expanded .agg-expanded').each(function(){$('.agg-tab').each(function(){$(this).removeClass('active');});$(this).fadeOut().clone().appendTo(hiddenContainer);$(this).remove();});elem.addClass('active');target.clone().appendTo(targetContainer).fadeIn();target.remove();}else{$('.agg-content-expanded .agg-expanded').each(function(){$('.agg-tab').each(function(){$(this).removeClass('active');});$(this).fadeOut().clone().appendTo(hiddenContainer);$(this).remove();});}}
var rotateBucket=function(){var currentFAB=$('#featured-alumni .active'),firstFAB=currentFAB.parent('#featured-alumni').children('div').eq(0),nextFAB=currentFAB.next(),currentFFB=$('#featured-faculty .active'),firstFFB=currentFFB.parent('#featured-faculty').children('div').eq(0),nextFFB=currentFFB.next(),currentFSB=$('#featured-student-innovation-project .active'),firstFSB=currentFSB.parent('#featured-student-innovation-project').children('div').eq(0),nextFSB=currentFSB.next();if(!currentFAB.is(':last-child')){currentFAB.removeClass('active').addClass('hidden').next().addClass('active').removeClass('hidden');}else{currentFAB.removeClass('active').addClass('hidden').parent('#featured-alumni').children('div').eq(0).addClass('active').removeClass('hidden');}
if(!currentFFB.is(':last-child')){currentFFB.removeClass('active').addClass('hidden').next().addClass('active').removeClass('hidden');}else{currentFFB.removeClass('active').addClass('hidden').parent('#featured-faculty').children('div').eq(0).addClass('active').removeClass('hidden');}
if(!currentFSB.is(':last-child')){currentFSB.removeClass('active').addClass('hidden').next().addClass('active').removeClass('hidden');}else{currentFSB.removeClass('active').addClass('hidden').parent('#featured-student-innovation-project').children('div').eq(0).addClass('active').removeClass('hidden');}}
var heroSliderFunction=function(){if($('.heroSlider').length>0){$('.heroSlider').iosSlider({snapToChildren:true,desktopClickDrag:true,infiniteSlider:true,navSlideSelector:$('.slider-nav .slider-button'),autoSlide:false,autoSlideTimer:9000,autoSlideTransTimer:500,onSlideChange:selectorChange,});}}
var selectorChange=function(args){$('.slider-nav .slider-button.current').removeClass('current');$('.slider-nav .slider-button').eq(args.currentSlideNumber-1).addClass('current');}
var techTrekEventFormat=function(){if($('.techtrek-schedule').length>=1){var discoveryExpo=$('.techtrek-schedule').find('[data-event="discovery-expo"]');var technologyForum=$('.techtrek-schedule').find('[data-event="technology-forum"]');if(discoveryExpo.length>=3){for(var i=0;i<discoveryExpo.length;i+=3){discoveryExpo.slice(i,i+3).wrapAll("<div class='row fix-height discovery-expo-wrapper'></div>");discoveryExpo.addClass('one-third');discoveryExpo.slice(1).addClass('border').addClass('left-border');}}else{for(var i=0;i<discoveryExpo.length;i+=2){discoveryExpo.slice(i,i+2).wrapAll("<div class='row fix-height discovery-expo-wrapper'></div>");discoveryExpo.addClass('one-half');discoveryExpo.slice(1).addClass('border').addClass('left-border');}}
if(technologyForum.length>=3){for(var i=0;i<technologyForum.length;i+=3){technologyForum.slice(i,i+3).wrapAll("<div class='row fix-height techtrek-schedule-wrapper'></div>");technologyForum.addClass('one-third');technologyForum.slice(1).addClass('border').addClass('left-border');}}else{for(var i=0;i<technologyForum.length;i+=2){technologyForum.slice(i,i+2).wrapAll("<div class='row fix-height techtrek-schedule-wrapper'></div>");technologyForum.addClass('one-half');technologyForum.slice(1).addClass('border').addClass('left-border');}}
if($('.techtrek-schedule').find('.discovery-expo-wrapper').length&&$('.techtrek-schedule').find('.techtrek-schedule-wrapper').length){$('.techtrek-schedule .discovery-expo-wrapper').last().addClass('border').addClass('bottom-border').addClass('full-width');$('.techtrek-schedule .techtrek-schedule-wrapper').last().addClass('no-margin').addClass('bottom-margin');}else if($('.techtrek-schedule').find('.discovery-expo-wrapper').length&&!$('.techtrek-schedule').find('.techtrek-schedule-wrapper').length){$('.techtrek-schedule .discovery-expo-wrapper').last().addClass('no-margin').addClass('bottom-margin');}else if(!$('.techtrek-schedule').find('.discovery-expo-wrapper').length&&$('.techtrek-schedule').find('.techtrek-schedule-wrapper').length){$('.techtrek-schedule .techtrek-schedule-wrapper').last().addClass('no-margin').addClass('bottom-margin');}}
if($('.techtrek-schedule .scheduled-event.overnight').length>=1){$('.scheduled-event.overnight').css({'width':$('.scheduled-event.overnight').parents('.bucket-content').width()});}}
var techTrekHeaderFix=function(){if($('#techtrek-header').length>=1){$('.header-motion').css({'height':$('.header-motion img').height()});if($('#techtrek-header')[0].scrollHeight>$('#upcoming-events')[0].scrollHeight){$('#upcoming-events').css({'height':$('#techtrek-header')[0].scrollHeight});console.log('height changed to '+$('#techtrek-header')[0].scrollHeight);}else{console.log('height left alone');}}}
var headerMotion=function(){$('.header-motion').animate({'background-position':'-1640px'},60000,'linear',function(){$('.header-motion').delay(2000).animate({'background-position':'0px'},60000,'linear')});}
var headerMotion2=function(){$('.header2').animate({'background-position':'1640px'},120000,'linear');}
$(document).ready(function(){!function(factory){"function"==typeof define&&define.amd?define(["jquery"],factory):factory("object"==typeof exports?require("jquery"):jQuery);}(function($){var caretTimeoutId,ua=navigator.userAgent,iPhone=/iphone/i.test(ua),chrome=/chrome/i.test(ua),android=/android/i.test(ua);$.mask={definitions:{"9":"[0-9]",a:"[A-Za-z]","*":"[A-Za-z0-9]"},autoclear:!0,dataName:"rawMaskFn",placeholder:"_"},$.fn.extend({caret:function(begin,end){var range;if(0!==this.length&&!this.is(":hidden"))return"number"==typeof begin?(end="number"==typeof end?end:begin,this.each(function(){this.setSelectionRange?this.setSelectionRange(begin,end):this.createTextRange&&(range=this.createTextRange(),range.collapse(!0),range.moveEnd("character",end),range.moveStart("character",begin),range.select());})):(this[0].setSelectionRange?(begin=this[0].selectionStart,end=this[0].selectionEnd):document.selection&&document.selection.createRange&&(range=document.selection.createRange(),begin=0-range.duplicate().moveStart("character",-1e5),end=begin+range.text.length),{begin:begin,end:end});},unmask:function(){return this.trigger("unmask");},mask:function(mask,settings){var input,defs,tests,partialPosition,firstNonMaskPos,lastRequiredNonMaskPos,len,oldVal;if(!mask&&this.length>0){input=$(this[0]);var fn=input.data($.mask.dataName);return fn?fn():void 0;}
return settings=$.extend({autoclear:$.mask.autoclear,placeholder:$.mask.placeholder,completed:null},settings),defs=$.mask.definitions,tests=[],partialPosition=len=mask.length,firstNonMaskPos=null,$.each(mask.split(""),function(i,c){"?"==c?(len--,partialPosition=i):defs[c]?(tests.push(new RegExp(defs[c])),null===firstNonMaskPos&&(firstNonMaskPos=tests.length-1),partialPosition>i&&(lastRequiredNonMaskPos=tests.length-1)):tests.push(null);}),this.trigger("unmask").each(function(){function tryFireCompleted(){if(settings.completed){for(var i=firstNonMaskPos;lastRequiredNonMaskPos>=i;i++)if(tests[i]&&buffer[i]===getPlaceholder(i))return;settings.completed.call(input);}}
function getPlaceholder(i){return settings.placeholder.charAt(i<settings.placeholder.length?i:0);}
function seekNext(pos){for(;++pos<len&&!tests[pos];);return pos;}
function seekPrev(pos){for(;--pos>=0&&!tests[pos];);return pos;}
function shiftL(begin,end){var i,j;if(!(0>begin)){for(i=begin,j=seekNext(end);len>i;i++)if(tests[i]){if(!(len>j&&tests[i].test(buffer[j])))break;buffer[i]=buffer[j],buffer[j]=getPlaceholder(j),j=seekNext(j);}
writeBuffer(),input.caret(Math.max(firstNonMaskPos,begin));}}
function shiftR(pos){var i,c,j,t;for(i=pos,c=getPlaceholder(pos);len>i;i++)if(tests[i]){if(j=seekNext(i),t=buffer[i],buffer[i]=c,!(len>j&&tests[j].test(t)))break;c=t;}}
function androidInputEvent(){var curVal=input.val(),pos=input.caret();if(curVal.length<oldVal.length){for(checkVal(!0);pos.begin>0&&!tests[pos.begin-1];)pos.begin--;if(0===pos.begin)for(;pos.begin<firstNonMaskPos&&!tests[pos.begin];)pos.begin++;input.caret(pos.begin,pos.begin);}else{for(checkVal(!0);pos.begin<len&&!tests[pos.begin];)pos.begin++;input.caret(pos.begin,pos.begin);}
tryFireCompleted();}
function blurEvent(){checkVal(),input.val()!=focusText&&input.change();}
function keydownEvent(e){if(!input.prop("readonly")){var pos,begin,end,k=e.which||e.keyCode;oldVal=input.val(),8===k||46===k||iPhone&&127===k?(pos=input.caret(),begin=pos.begin,end=pos.end,end-begin===0&&(begin=46!==k?seekPrev(begin):end=seekNext(begin-1),end=46===k?seekNext(end):end),clearBuffer(begin,end),shiftL(begin,end-1),e.preventDefault()):13===k?blurEvent.call(this,e):27===k&&(input.val(focusText),input.caret(0,checkVal()),e.preventDefault());}}
function keypressEvent(e){if(!input.prop("readonly")){var p,c,next,k=e.which||e.keyCode,pos=input.caret();if(!(e.ctrlKey||e.altKey||e.metaKey||32>k)&&k&&13!==k){if(pos.end-pos.begin!==0&&(clearBuffer(pos.begin,pos.end),shiftL(pos.begin,pos.end-1)),p=seekNext(pos.begin-1),len>p&&(c=String.fromCharCode(k),tests[p].test(c))){if(shiftR(p),buffer[p]=c,writeBuffer(),next=seekNext(p),android){var proxy=function(){$.proxy($.fn.caret,input,next)();};setTimeout(proxy,0);}else input.caret(next);pos.begin<=lastRequiredNonMaskPos&&tryFireCompleted();}
e.preventDefault();}}}
function clearBuffer(start,end){var i;for(i=start;end>i&&len>i;i++)tests[i]&&(buffer[i]=getPlaceholder(i));}
function writeBuffer(){input.val(buffer.join(""));}
function checkVal(allow){var i,c,pos,test=input.val(),lastMatch=-1;for(i=0,pos=0;len>i;i++)if(tests[i]){for(buffer[i]=getPlaceholder(i);pos++<test.length;)if(c=test.charAt(pos-1),tests[i].test(c)){buffer[i]=c,lastMatch=i;break;}
if(pos>test.length){clearBuffer(i+1,len);break;}}else buffer[i]===test.charAt(pos)&&pos++,partialPosition>i&&(lastMatch=i);return allow?writeBuffer():partialPosition>lastMatch+1?settings.autoclear||buffer.join("")===defaultBuffer?(input.val()&&input.val(""),clearBuffer(0,len)):writeBuffer():(writeBuffer(),input.val(input.val().substring(0,lastMatch+1))),partialPosition?i:firstNonMaskPos;}
var input=$(this),buffer=$.map(mask.split(""),function(c,i){return"?"!=c?defs[c]?getPlaceholder(i):c:void 0;}),defaultBuffer=buffer.join(""),focusText=input.val();input.data($.mask.dataName,function(){return $.map(buffer,function(c,i){return tests[i]&&c!=getPlaceholder(i)?c:null;}).join("");}),input.one("unmask",function(){input.off(".mask").removeData($.mask.dataName);}).on("focus.mask",function(){if(!input.prop("readonly")){clearTimeout(caretTimeoutId);var pos;focusText=input.val(),pos=checkVal(),caretTimeoutId=setTimeout(function(){writeBuffer(),pos==mask.replace("?","").length?input.caret(0,pos):input.caret(pos);},10);}}).on("blur.mask",blurEvent).on("keydown.mask",keydownEvent).on("keypress.mask",keypressEvent).on("input.mask paste.mask",function(){input.prop("readonly")||setTimeout(function(){var pos=checkVal(!0);input.caret(pos),tryFireCompleted();},0);}),chrome&&android&&input.off("input.mask").on("input.mask",androidInputEvent),checkVal();});}});});$("#phone").mask("(999) 999-9999");});$('button.read-more').click(function(){if($(this).prev().hasClass('hide-content')){$(this).prev('.hide-content').toggleClass('hidden');$(this).text('read more');if($(this).prev('.hide-content').hasClass('hidden')){$(this).text('read more');}else{$(this).text('less');}}else if($(this).parent().prev().hasClass('hide-content')){$(this).parent().prev('.hide-content').toggleClass('hidden');if($(this).parent().prev('.hide-content').hasClass('hidden')){$(this).text('read more');}else{$(this).text('less');}}});$(document).ready(function(){$('.img-pop-content').on('click',function(){var imgPopSrc=$(this).attr('src');var imgPopInfo=$(this).siblings('.img-pop-info').text();$('html, body').css({'overflow':'hidden'});$('body').prepend("<div class='img-pop-container'>"+"<style>"+"@keyframes imgPopFadeIn {0%{opacity: 0;} 100%{opacity: 1;}}"+"@keyframes imgPopImgIn {0%{top: -200px;}100%{top 0px;}}"+"</style>"+"<div class='close-img-pop-cont'>"+"<div><p class='img-pop-caption'>"+imgPopInfo+"</p></div>"+"<div class='close-img-pop'>X</div>"+"</div>"+"<div>"+"<div class='img-pop'>"+"<img src='"+imgPopSrc+"'>"+"</div>"+"</div>"+"</div>");$('.close-img-pop').on('click',function(){$('.img-pop-container').remove();$('html, body').css({'overflow':'auto'});});})})
$(document).ready(function(){if(window.location.hash=="#accreditation-info"){console.log("hi");$('html, body').animate({scrollTop:$('#accreditation-info').offset().top-20},'fast');}});

$(document).on('click','#submit-rsvp',function(){
	if (typeof(Storage) !== "undefined") {
	    localStorage.setItem("popup", "hide");
	}
})

$(window).scroll(function() {
	if ( $(window).scrollTop() > 16 ){
		$('#bottomnav').addClass('bottomrise');
	} else {
		$('#bottomnav').removeClass('bottomrise');
	}
});